name: gashopper

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.5

  google_fonts: ^6.2.1

  # Network
  dio: ^5.3.2

  internet_connection_checker: ^1.0.0+1

  # UI Components
  cached_network_image: ^3.3.0

  flutter_svg: ^2.0.9

  shimmer: ^3.0.0

  hive: ^2.2.3

  hive_flutter: ^1.1.0

  # Utils
  intl: ^0.18.1

  json_annotation: ^4.8.1

  intl_phone_field: ^3.2.0

  image_picker: ^1.1.2

  mobile_scanner: ^6.0.2

  permission_handler: ^11.0.1

  dropdown_button2: ^2.3.9

  sms_autofill: ^2.4.0

  share_plus: ^10.0.2

  pdf: ^3.11.1

  path_provider: ^2.1.1

  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  flutter_launcher_icons: ^0.13.1

  # Code Generation
  build_runner: ^2.4.7

  hive_generator: ^2.0.1

  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  image_path: "assets/icons/app-icon.png"
  android: "launcher_icon"
  ios: true
